"""
Fix proposal mode -- writes the Blue Agent's mitigations to reviewable files.

This does NOT edit your source. The Blue Agent produces prose describing a fix,
not a patch, so there is nothing to apply. Each proposal is written to a
markdown file for a human to read and implement.

Committing proposals to a branch is opt-in (`create_branch=True`). It is not the
default: writing to a user's repository is a side effect they should ask for,
and an earlier version of this module did it unconditionally.
"""

from __future__ import annotations

import asyncio
import os
from dataclasses import dataclass, field

from redteam_arena.types import Battle, Err, Finding, Mitigation, Ok, Result

PROPOSAL_DIR = ".redteam-fixes"


@dataclass
class FixResult:
    finding_id: str
    file_path: str
    description: str
    branch: str = ""
    written: bool = False
    proposal_path: str = ""
    reason: str = ""


@dataclass
class AutoFixSummary:
    total_findings: int
    fixable_findings: int
    proposals_written: int
    proposals_skipped: int
    output_dir: str = ""
    fixes: list[FixResult] = field(default_factory=list)


def _get_fixable_pairs(
    battle: Battle,
) -> list[tuple[Finding, Mitigation]]:
    """Pair findings with high/medium-confidence mitigations."""
    all_findings = [f for r in battle.rounds for f in r.findings]
    all_mitigations = [m for r in battle.rounds for m in r.mitigations]

    pairs: list[tuple[Finding, Mitigation]] = []
    for finding in all_findings:
        mitigation = next(
            (
                m
                for m in all_mitigations
                if m.finding_id == finding.id
                and m.confidence in ("high", "medium")
            ),
            None,
        )
        if mitigation:
            pairs.append((finding, mitigation))

    # Sort by severity: critical first
    order = {"critical": 0, "high": 1, "medium": 2, "low": 3}
    pairs.sort(key=lambda p: order.get(p[0].severity, 4))

    return pairs


def _sanitize_branch_name(name: str) -> str:
    """Sanitize a string for use in a git branch name."""
    result = name.lower()
    clean = ""
    for ch in result:
        if ch.isalnum() or ch == "-":
            clean += ch
        else:
            clean += "-"
    # Collapse multiple dashes
    while "--" in clean:
        clean = clean.replace("--", "-")
    clean = clean.strip("-")
    return clean[:40]


def _generate_fix_description(finding: Finding, mitigation: Mitigation) -> str:
    """Generate a fix proposal file's content."""
    lines: list[str] = []
    lines.append(f"# Fix Proposal: {finding.description[:80]}")
    lines.append("")
    lines.append("> This is a suggestion for a human to implement. No source file")
    lines.append("> has been modified, and the finding below is unverified model")
    lines.append("> output -- confirm it is real before acting on it.")
    lines.append("")
    lines.append(f"**Severity (model-assigned):** {finding.severity.upper()}")
    lines.append(f"**Reported location:** `{finding.file_path}:{finding.line_reference}`")
    if finding.verification != "unchecked":
        lines.append(f"**Location check:** {finding.verification} — {finding.verification_detail}")
    lines.append(f"**Finding ID:** {finding.id}")
    lines.append("")
    lines.append("## Reported Vulnerability")
    lines.append("")
    lines.append(finding.description)
    lines.append("")
    lines.append(f"**Attack Vector:** {finding.attack_vector}")
    lines.append("")
    if finding.code_snippet:
        lines.append("**Model-quoted code:**")
        lines.append("```")
        lines.append(finding.code_snippet)
        lines.append("```")
        lines.append("")
    lines.append("## Proposed Fix")
    lines.append("")
    lines.append(f"**Model confidence:** {mitigation.confidence.upper()}")
    lines.append("")
    lines.append(f"> {mitigation.acknowledgment}")
    lines.append("")
    lines.append(mitigation.proposed_fix)
    lines.append("")
    lines.append("---")
    lines.append("*Generated by RedTeam Arena. Not applied, not verified — review required.*")
    return "\n".join(lines)


async def _run_git(target_dir: str, *args: str) -> tuple[int, str, str]:
    """Run a git command and return (returncode, stdout, stderr)."""
    proc = await asyncio.create_subprocess_exec(
        "git", *args,
        cwd=target_dir,
        stdout=asyncio.subprocess.PIPE,
        stderr=asyncio.subprocess.PIPE,
    )
    stdout, stderr = await proc.communicate()
    return (
        proc.returncode or 0,
        stdout.decode("utf-8", errors="replace").strip(),
        stderr.decode("utf-8", errors="replace").strip(),
    )


async def _git_or_raise(target_dir: str, *args: str) -> str:
    """Run a git command, raising if it fails.

    Every git call here must be checked. Previously none were, so a failed
    `checkout -b` did not stop the run and the subsequent commit landed on
    whatever branch the user happened to be on -- potentially main.
    """
    code, stdout, stderr = await _run_git(target_dir, *args)
    if code != 0:
        raise RuntimeError(f"git {' '.join(args)} failed: {stderr or stdout}")
    return stdout


async def _is_git_repo(target_dir: str) -> bool:
    code, stdout, _ = await _run_git(target_dir, "rev-parse", "--is-inside-work-tree")
    return code == 0 and stdout == "true"


async def _is_git_clean(target_dir: str) -> bool:
    code, stdout, _ = await _run_git(target_dir, "status", "--porcelain")
    return code == 0 and len(stdout) == 0


async def _get_current_branch(target_dir: str) -> str:
    code, stdout, _ = await _run_git(target_dir, "rev-parse", "--abbrev-ref", "HEAD")
    return stdout if code == 0 else "main"


async def run_auto_fix(
    target_dir: str,
    battle: Battle,
    *,
    create_branch: bool = False,
    dry_run: bool = False,
    output_dir: str = "",
) -> Result[AutoFixSummary, Exception]:
    """Write the Blue Agent's mitigations out as reviewable proposal files.

    No source file is modified. With create_branch=True each proposal is also
    committed to its own branch, and the original branch is always restored.
    """
    all_findings = [f for r in battle.rounds for f in r.findings]
    fixable_pairs = _get_fixable_pairs(battle)
    fixes: list[FixResult] = []

    proposal_dir = output_dir or os.path.join(target_dir, PROPOSAL_DIR)

    if create_branch and not dry_run:
        if not await _is_git_repo(target_dir):
            return Err(
                error=Exception(
                    f"{target_dir} is not a git repository, so fix branches "
                    "cannot be created. Re-run without branch creation to write "
                    "proposals as plain files."
                )
            )
        if not await _is_git_clean(target_dir):
            return Err(
                error=Exception(
                    "Working directory has uncommitted changes. "
                    "Commit or stash before creating fix branches."
                )
            )

    base_branch = await _get_current_branch(target_dir) if create_branch else ""

    try:
        for finding, mitigation in fixable_pairs:
            branch_name = (
                f"fix/redteam-{finding.id}-"
                f"{_sanitize_branch_name(finding.description)}"
            )

            if dry_run:
                fixes.append(
                    FixResult(
                        finding_id=finding.id,
                        file_path=finding.file_path,
                        description=finding.description,
                        branch=branch_name if create_branch else "",
                        written=False,
                        reason="Dry run -- nothing written",
                    )
                )
                continue

            try:
                if create_branch:
                    await _git_or_raise(
                        target_dir, "checkout", "-b", branch_name, base_branch
                    )

                os.makedirs(proposal_dir, exist_ok=True)
                proposal_path = os.path.join(proposal_dir, f"{finding.id}.md")
                with open(proposal_path, "w", encoding="utf-8") as f:
                    f.write(_generate_fix_description(finding, mitigation))

                if create_branch:
                    await _git_or_raise(target_dir, "add", proposal_path)
                    commit_msg = (
                        f"docs: fix proposal for {finding.severity} finding "
                        f"{finding.id}\n\n"
                        f"{finding.description[:200]}\n\n"
                        f"Reported location: {finding.file_path}:{finding.line_reference}\n"
                        f"Model confidence: {mitigation.confidence}\n\n"
                        "This commit contains a written proposal only. No source "
                        "file was modified, and the finding is unverified model "
                        "output."
                    )
                    await _git_or_raise(target_dir, "commit", "-m", commit_msg)
                    await _git_or_raise(target_dir, "checkout", base_branch)

                fixes.append(
                    FixResult(
                        finding_id=finding.id,
                        file_path=finding.file_path,
                        description=finding.description,
                        branch=branch_name if create_branch else "",
                        written=True,
                        proposal_path=proposal_path,
                    )
                )
            except Exception as exc:
                fixes.append(
                    FixResult(
                        finding_id=finding.id,
                        file_path=finding.file_path,
                        description=finding.description,
                        written=False,
                        reason=str(exc),
                    )
                )
    finally:
        # Always put the user back where they started, whatever went wrong.
        if create_branch and not dry_run and base_branch:
            await _run_git(target_dir, "checkout", base_branch)

    return Ok(
        value=AutoFixSummary(
            total_findings=len(all_findings),
            fixable_findings=len(fixable_pairs),
            proposals_written=sum(1 for f in fixes if f.written),
            proposals_skipped=sum(1 for f in fixes if not f.written),
            output_dir=proposal_dir,
            fixes=fixes,
        )
    )


def format_auto_fix_summary(summary: AutoFixSummary) -> str:
    """Format the proposal summary for terminal display."""
    lines: list[str] = []
    lines.append("")
    lines.append("  Fix Proposals")
    lines.append("  " + "=" * 40)
    lines.append(f"  Total findings:     {summary.total_findings}")
    lines.append(f"  With a mitigation:  {summary.fixable_findings}")
    lines.append(f"  Proposals written:  {summary.proposals_written}")
    lines.append(f"  Skipped:            {summary.proposals_skipped}")
    if summary.output_dir:
        lines.append(f"  Written to:         {summary.output_dir}")
    lines.append("")

    for fix in summary.fixes:
        status = "[WROTE]" if fix.written else "[SKIP] "
        lines.append(f"  {status} {fix.description[:60]}")
        if fix.branch:
            lines.append(f"          Branch: {fix.branch}")
        if fix.reason:
            lines.append(f"          Reason: {fix.reason}")

    lines.append("")
    lines.append("  These are written suggestions, not applied changes. No source")
    lines.append("  file was modified. Confirm each finding before implementing.")
    lines.append("")
    return "\n".join(lines)
