/**
 * Battle report generator — produces Markdown reports from Battle objects.
 */

import { writeFile } from "node:fs/promises";
import { join } from "node:path";
import type { Battle, Finding, Mitigation, Severity } from "../types.js";

const SEVERITY_EMOJI: Record<Severity, string> = {
  critical: "!!",
  high: "!",
  medium: "~",
  low: "-",
};

export function generateReport(battle: Battle): string {
  const allFindings = battle.rounds.flatMap((r) => r.findings);
  const allMitigations = battle.rounds.flatMap((r) => r.mitigations);

  const lines: string[] = [];

  // Header
  lines.push(`# RedTeam Arena Battle Report`);
  lines.push("");
  lines.push(`| Field | Value |`);
  lines.push(`|-------|-------|`);
  lines.push(`| **Battle ID** | ${battle.id} |`);
  lines.push(`| **Date** | ${battle.startedAt.toISOString()} |`);
  lines.push(`| **Scenario** | ${battle.config.scenario.name} |`);
  lines.push(`| **Target** | ${battle.config.targetDir} |`);
  lines.push(`| **Rounds** | ${battle.rounds.length} |`);
  lines.push(`| **Status** | ${battle.status} |`);
  lines.push("");

  // Summary
  lines.push(`## Summary`);
  lines.push("");

  const bySeverity = { critical: 0, high: 0, medium: 0, low: 0 };
  for (const f of allFindings) bySeverity[f.severity]++;

  lines.push(`| Severity | Count |`);
  lines.push(`|----------|-------|`);
  lines.push(`| Critical | ${bySeverity.critical} |`);
  lines.push(`| High | ${bySeverity.high} |`);
  lines.push(`| Medium | ${bySeverity.medium} |`);
  lines.push(`| Low | ${bySeverity.low} |`);
  lines.push(`| **Total** | **${allFindings.length}** |`);
  lines.push("");

  const coverage =
    allFindings.length > 0
      ? Math.round((allMitigations.length / allFindings.length) * 100)
      : 100;
  lines.push(
    `**Mitigations Proposed**: ${allMitigations.length}/${allFindings.length} (${coverage}%)`
  );
  lines.push("");

  // Findings Detail
  if (allFindings.length === 0) {
    lines.push(`## Findings`);
    lines.push("");
    lines.push(`No vulnerabilities found.`);
    lines.push("");
  } else {
    lines.push(`## Findings`);
    lines.push("");

    for (let i = 0; i < allFindings.length; i++) {
      const finding = allFindings[i];
      const mitigation = allMitigations.find(
        (m) => m.findingId === finding.id
      );

      lines.push(
        `### ${SEVERITY_EMOJI[finding.severity]} Finding ${i + 1}: ${finding.description.slice(0, 80)}`
      );
      lines.push("");
      lines.push(`| Field | Value |`);
      lines.push(`|-------|-------|`);
      lines.push(
        `| **Severity** | ${finding.severity.toUpperCase()} |`
      );
      lines.push(
        `| **File** | \`${finding.filePath}:${finding.lineReference}\` |`
      );
      lines.push(`| **Attack Vector** | ${finding.attackVector} |`);
      lines.push(`| **Round** | ${finding.roundNumber} |`);
      lines.push("");

      if (finding.codeSnippet) {
        lines.push(`**Vulnerable Code**:`);
        lines.push("```");
        lines.push(finding.codeSnippet);
        lines.push("```");
        lines.push("");
      }

      if (mitigation) {
        lines.push(
          `**Mitigation** (Confidence: ${mitigation.confidence.toUpperCase()}):`
        );
        lines.push("");
        lines.push(`> ${mitigation.acknowledgment}`);
        lines.push("");
        lines.push(`**Proposed Fix**: ${mitigation.proposedFix}`);
        lines.push("");
      }

      lines.push("---");
      lines.push("");
    }
  }

  // Battle Log
  lines.push(`## Battle Log`);
  lines.push("");
  lines.push(`<details>`);
  lines.push(`<summary>Click to expand full battle log</summary>`);
  lines.push("");

  for (const round of battle.rounds) {
    lines.push(`### Round ${round.number}`);
    lines.push("");
    lines.push(`**Red Agent Output:**`);
    lines.push("```");
    lines.push(round.redRawOutput.slice(0, 2000));
    if (round.redRawOutput.length > 2000) lines.push("... (truncated)");
    lines.push("```");
    lines.push("");
    lines.push(`**Blue Agent Output:**`);
    lines.push("```");
    lines.push(round.blueRawOutput.slice(0, 2000));
    if (round.blueRawOutput.length > 2000) lines.push("... (truncated)");
    lines.push("```");
    lines.push("");
  }

  lines.push(`</details>`);
  lines.push("");

  // Footer
  lines.push("---");
  lines.push(
    `*Generated by [RedTeam Arena](https://github.com/DilawarShafiq/redteam-arena) v0.1.0*`
  );

  return lines.join("\n");
}

export async function writeReport(
  content: string,
  battleId: string
): Promise<string> {
  const filename = `redteam-report-${battleId}.md`;
  const filepath = join(process.cwd(), filename);
  await writeFile(filepath, content, "utf-8");
  return filepath;
}
